### ISSUE TITLE
Similar project, different approach

### ISSUE THREAD

**Issue by kmturley** [DISTRHO/PawPaw#11]
Hi there,
Your project looks interesting, building cross-platform plugins in an automated way.

I've also been trying to solve this problem and come up with a slightly different approach. It could be useful for your project. Instead of trying to create an uber single project which can build any type of plugin, separating them into framework-specific projects.

My approach:

- Template repo named after a framework (Dplug, iPlug, JUCE, Steinberg)
- Framework as a git submodule (so it's linked but not stored in the same repo and don't infringe copyright)
- ./src/ folder to contain any custom code/assets
- README.md containing the commands to build the plugin locally
- ./github/workflows folder containing the release workflow to build the commands cross-platform

So far i've created boilerplate repos for the main framework types here:

- https://github.com/studiorack/studiorack-plugin-dplug
- https://github.com/studiorack/studiorack-plugin-iplug
- https://github.com/studiorack/studiorack-plugin-juce
- https://github.com/studiorack/studiorack-plugin-steinberg

Feel free to copy/reused the same approach :)

If we can help plugin developers to start structuring their plugins with automated builds, they will save time, there will be more compatibility and everyone will benefit!

**Comment by falkTX** [comment]
I should have left a comment on here before, but was unsure how to reply.

It is not my purpose to setup templates, the PawPaw stuff is first of all for dealing with building static libs. the plugin collection provides a nice showcase for it and helps to spread the LV2 format to non-Linux systems.
Developers can add the deps through PawPaw if they want, I added it in my https://github.com/DISTRHO/dpf-cmake-action that helps to automate DPF builds and releases.
I am also using PawPaw as the static lib setup for Carla and JACK2 releases.
And https://github.com/brummer10/Fluida.lv2/ is an example of a project using PawPaw to deal with static linkage

So it is already in use, its public and free, others can use it too if they so wish. That is enough for me.

**Comment by kmturley** [comment]
Ah yes I see you are already doing it with:
https://github.com/DISTRHO/dpf-cmake-action

You have a GitHub workflow steps called `Build dependencies through PawPaw`:
https://github.com/DISTRHO/dpf-cmake-action/blob/2f059677ebed1edda495e5a5d9881066dfc66c20/action.yml#L251

Which downloads and installs this repo:
https://github.com/DISTRHO/PawPaw

I wonder if you should make this pattern more explicit in the README for this repo?
I don't see any mention of `dpf-cmake-action` or GitHub workflows and automation.
