### ISSUE TITLE
Add Odin2 Synth

### ISSUE THREAD

**Issue by MrTeeXD** [DISTRHO/PawPaw#12]
Hey there, I don't know if this is the correct place to suggest Plugins but lately, I have really been liking the Open Source Synth called Odin2 but I noticed there is no LV2 Version of it and I really don't wanna use VST's anymore, would it be a possibility to add Odin2 to the list?

**Comment by falkTX** [comment]
Yeah, I need to figure out something for the all new juce-based plugins.
a way to make an lv2 version easier to have available.
