### ISSUE TITLE
calf plug for windows

### ISSUE THREAD

**Issue by Reaper10** [DISTRHO/PawPaw#14]
Could you add the calf plug so us on windows can use these awesome plugin.

**Comment by falkTX** [comment]
This is a little bit promising..

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1334853/129943871-6faa3d2b-590e-4548-af53-c8281b7a217c.png">

for macos, not windows. but shows we can build on other archs that are not linux.
still no gui, yeah.

**Comment by falkTX** [comment]
closing, decided against gtk2 based plugins
