### ISSUE TITLE
LSP plugins

### ISSUE THREAD

**Issue by Reaper10** [DISTRHO/PawPaw#15]
Do you think you could add the LSP plugin bundle? Or is even possible?

**Comment by falkTX** [comment]
Can they be built for macOS or windows?
Last time I checked it was very tied to linux/unix/posix so having it work on windows would not be so simple.

@sadko4u what is the status here?

**Comment by sadko4u** [comment]
After releasing 1.2.0, I'll concentrate more effort on porting plugins to other platforms.
At least, the main problem is UI. Backend core modules are alreay almost compatible with at least Windows platform.

**Comment by Tarek-Hasan** [comment]
As of v1.2.3, lsp-tk-lib has been ported to Windows.

**Comment by sadko4u** [comment]
Yes, that's true but the entire bundle is still not ported to Windows yet.

**Comment by Tarek-Hasan** [comment]
As of v1.2.6, LSP can be compiled for Windows.

**Comment by Tarek-Hasan** [comment]
@sadko4u is LSP ready for windows release now?
falkTX, last release is 3 years old, please make a new release.

**Comment by falkTX** [comment]
> It is possible to build LSP Plugins for Windows now but we still don't ship binaries for Windows because we're founding some financial model around Windows builds.

on that case it is best to not build the plugins from here, similar to the situation of x42-plugins where it is easy to build them with pawpaw but I end up not doing it out of respect for the authors

closing ticket as not planned
