### ISSUE TITLE
b. music plugin

### ISSUE THREAD

**Issue by Reaper10** [DISTRHO/PawPaw#22]
Just asking about the [b. music plugin](https://github.com/sjaehn).

**Comment by falkTX** [comment]
Not sure if those work on anything other than Linux/X11. @sjaehn can you comment?

**Comment by sjaehn** [comment]
Yes they are X11 only, yet. One little single file would break the compatibility. It's screen.c which you can find in the src folder of each plugin.

This file contains two simple functions to get the screen size to find an acceptable ui size and is called upon plugin instantiation. Till now, I only implemented an X11 version. I have Windows and Mac on my TODO list. For a wile. But I didn't find time yet. And I'm busy with sth. else at the moment. So, if somebody else wants to take hands on ... :-)

Then at least all plugins without `BWidgets::FileChooser` (uses POSIX) should work: B.Slizr, B.Choppr, B.Shapr, B.Angr, and B.Schaffl. But no guarantees - as I didn't test it.

**Comment by falkTX** [comment]
doing a round of cleanup, closing and leaving it to others to do the non-linux porting if they so choose.
I am sure they would appreciate contributions too, but I have enough on my plate already so closing as wont-fix.
