### ISSUE TITLE
No UI for DIE Fluidsynth on March 16 1.1 release on Windows so can't select sf2

### ISSUE THREAD

**Issue by Someone65** [DISTRHO/PawPaw#23]
As the title states, a number of plugins don't have a UI which works just fine for most plugins except this one. I can't find a way to select an sf2 file because there's nothing to press to do so. 

Running this through REAPER, this is how it looks like:
![Screenshot of UI](https://i.imgur.com/nmQwm36.png)

**Comment by falkTX** [comment]
This is a feature and not a bug.
There is no UIs at all for DIE plugins.

Reaper is simply missing support for atom/parameter based file paths.

If you load it in Ardour, you will clearly see the file path parameter.
![Screenshot_20211213_165111](https://user-images.githubusercontent.com/1334853/145854166-74700ddc-85c1-4db7-b4ce-61fda65cd7e0.png)

So this is something to report to reaper devs to implement.
