### ISSUE TITLE
Used Fluidsynth version is quite old

### ISSUE THREAD

**Issue by arseniiv** [DISTRHO/PawPaw#29]
Hi, can Fluidsynth version be upped to at least 2.2.2? 🙂

(I went upstream from this issue: [https://github.com/brummer10/Fluida.lv2/issues/32](https://github.com/brummer10/Fluida.lv2/issues/32).)

**Comment by arseniiv** [comment]
@falkTX I know I shouldn’t tag people just for the sake of it, but have you seen this? Sorry to grab attention like that, I’d just be very grateful to know how hard it is to do, at least, and if you have time some other day. 🙂🙏

**Comment by falkTX** [comment]
i have seen this yes, but this is something that is better handled by a PR to update it.

see https://github.com/DISTRHO/PawPaw/blob/main/bootstrap-plugins.sh#L557 for the current setup and https://github.com/DISTRHO/PawPaw/tree/main/patches/fluidsynth for current patches applied to it.

**Comment by falkTX** [comment]
fluidsynth is updated, verified to work with https://github.com/brummer10/Fluida.lv2

**Comment by arseniiv** [comment]
2.0.0 is great but can it be upgraded further to 2.2.2 later (the first release that fixed microtuning)? Thanks! 👏
