### ISSUE TITLE
builds are not signed

### ISSUE THREAD

**Issue by Be-ing** [DISTRHO/PawPaw#8]
Installing the 1.0 release build on Windows warns about installing an unsigned executable. I haven't tested on macOS.

**Comment by falkTX** [comment]
It is the same on macOS.

I haven't researched this yet. But I suspect it will be very costly.
As you can imagine, my interest to pay what is basically fee to get these programs without warnings is very small.

**Comment by Be-ing** [comment]
It's not free for Windows but it's not super expensive. I totally understand not wanting to pay for it though.

I think it might be free on macOS.

**Comment by Be-ing** [comment]
$85 per year: https://comodosslstore.com/codesigning.aspx

**Comment by falkTX** [comment]
doing a round of bug checking, closing this as not-wanted.

I started to use PawPaw more and more for all my static libs needs, where it is now more about the libs then the plugin collection.
And for plugins I am still not convinced paying security-theater fees is worth anything.
